version: "3.8"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: projecttracker
    volumes:
      - dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/projecttracker"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
    dev_data:
