# Generated by Django 3.2 on 2022-01-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projecttracker', '0001_createsuperuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nick', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('employees', models.ManyToManyField(related_name='projects', to='projecttracker.Employee', verbose_name='List of employees')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(default=None)),
                ('leader', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='leading_projects', to='projecttracker.employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projecttracker.team')),
            ],
            options={
                'verbose_name_plural': 'projects',
            },
        ),
    ]
