name: Python Tests

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: cp .env.local .env && docker-compose up -d db
    - name: Check running containers
      run: docker ps -a
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests with pytest
      run: pytest